### ISSUE TITLE
Bug in filtering rows containing NaN

### ISSUE THREAD

**Issue by qibinc** [sola-st/IdBench#2]
Hi,

We find the following possible bug in the `compute_correlations.py` file, which concerns the effectiveness of the benchmark and affects the bar charts in the paper.

https://github.com/sola-st/IdBench/blob/42243541dee0da754acc1bf734fdcf6f40628db8/compute_correlations.py#L187-L194

The `row_filter` function here filters out a row whenever there is a column with a NaN value, while the intended behavior should be only filtering when the human score of the current `kind` (one relatedness, similarity, contextual similarity) is NaN. With the current code, an instance is only valid if all of the scores are not NaN.

This has severe influence on the benchmark. For example, in the small benchmark, there are 166 valid scores for relatedness and similarity which can be used for evaluation. With this code, only 54 are actually used, making the small benchmark extremely unreliable.

We suggest change the code to the following:

```python
        def get_row_filter(kind):
            def row_filter(r):
                if r[kind] == "NAN":
                    return False
                return True
            return row_filter

        for kind in kinds:
            filtered_pairs = pairs[pairs.apply(get_row_filter(kind), axis=1)]
```

**Comment by michaelpradel** [comment]
Thanks for pointing this out! Our filtering indeed has been more strict than needed. I've just pushed a fix (commit 821df66). It makes the benchmark more stable, and fortunately, doesn't impact the overall conclusions we draw in the paper.

Note that my fix is slightly different than your suggestion. Your suggested change would keep the pairs for which some of the studied embeddings don't provide a score (i.e., are "NAN"). Instead, my fix filters those away, so that the overall correlation is computed on the same set of identifier pairs for each benchmark size. For example, for "small", it keeps 154 pairs.
